# Basics of Scipy's rotation submodule

> **Goal**: TODO

TODO -> Explain briefly the group of all rotations in the 3D Cartesian space and how it works using Scipy's submodule rotations

For details see: https://dfki-ric.github.io/pytransform3d/rotations.html

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as r

In [2]:
# define a rotation using Euler angles (Bunge convention)
rotation = r.from_euler('zxz', [30, 45, 40], degrees=True)

In [3]:
print(f"Euler angles: {rotation.as_euler('zxz', degrees=True)} (Bunge convention)")
print(f"Euler angles: {rotation.as_euler('zxy', degrees=True)} (Other convention)")
print(f"Quaternions: {rotation.as_quat()}")
print(f"Rotation vectors: {rotation.as_rotvec(degrees=True)}")
print(f"Modified Rodrigues Parameters: {rotation.as_mrp()}")
print(f"Rotation matrix: \n {rotation.as_matrix()}")

Euler angles: [30. 45. 40.] (Bunge convention)
Euler angles: [79.87925979 32.79775133 32.73240721] (Other convention)
Quaternions: [0.38122721 0.03335306 0.52991553 0.75679781]
Rotation vectors: [47.61167346  4.16548168 66.18143918]
Modified Rodrigues Parameters: [0.21700119 0.01898514 0.30163718]
Rotation matrix: 
 [[ 0.43615421 -0.77664764  0.45451948]
 [ 0.82750801  0.1477107  -0.54167522]
 [ 0.35355339  0.61237244  0.70710678]]


In [4]:
np.around(rotation.as_quat(), decimals=4)

array([0.3812, 0.0334, 0.5299, 0.7568])

In [5]:
import sys
import scipy as sp
import matplotlib as mpl
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)
print('Numpy', np.__version__)
print('Scipy', sp.__version__)
print('Matplolib', mpl.__version__)

Notebook tested in 2023-02-02 using:
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Numpy 1.23.5
Scipy 1.9.3
Matplolib 3.6.2
