# Basics of Scipy's rotation submodule

> **Goal**: Briefly explain all the common ways of representing a rotation in 3D Cartesian space and how they work using Scipy's Rotation submodule. The purpose of using Scipy for rotations and not a specific library (e.g. https://dfki-ric.github.io/pytransform3d/) is to keep dependencies to a minimum (Scipy will also be used for minimisation).

Scipy's rotation module provides the following ways of representing a 3D rotation

- Rotation Matrices
- Euler Angles
- Quaternions
- Rotation Vectors (a.k.a. Euler axis and angle or axis-angle pair)
- Modified Rodrigues Parameters (a.k.a. Log map or logarithm of rotation)

as well as different operations on rotations and transformations between them. There is **no representation** that is non-redundant, continuous, and free of singularities. Below is a table summarising their properties:

|          **Representation**          |  **Inverse**  | **Rotation of vector** | **Concatenation** | **Interpolation** | **Scipy name** |
| :----------------------------------: | :-----------: | :--------------------: | :---------------: | :---------------: | :------------: |
|         Rotation matrix $R$          |   Transpose   |          Yes           |        Yes        |        No         |     matrix     |
| Euler angles ($\alpha,\beta,\gamma$) |      No       |           No           |        No         |        No         |     euler      |
|           Quaternion ($q$)           |   Conjugate   |          Yes           |        Yes        |        Yes        |      quat      |
|     Axis-angle ($\omega,\theta$)     | Negative axis |           No           |        No         |        Yes        |     rotvec     |
|    Rodrigues parameters ($\omega$)   |    Negative   |           No           |        No         |       (Yes)       |      mrp       |


For more details see:  
https://dfki-ric.github.io/pytransform3d/rotations.html (most of the info here is based on the documentation of this Python module)  
https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as r

After importing _Rotation as r_ from _scipy.spatial.transform_, rotations are defined by the following way:  

``r.from_<representation>(parameters)``  

where the representation of the rotation can be of any type defined in the table (Scipy name) and the input parameters depend on the type of representation: For example:

In [2]:
# define a rotation using Euler angles (Bunge convention)
rotation = r.from_euler('zxz', [30, 45, 40], degrees=True)

and transformed using:  

``r.as_<representation>(parameters)`` 

In [3]:
rotation.as_quat()

array([0.38122721, 0.03335306, 0.52991553, 0.75679781])

Below I show some formated examples using f-strings

In [4]:
print(f"Euler angles:     {rotation.as_euler('zxz', degrees=True)} (Bunge convention)")
print(f"Euler angles:     {np.around(rotation.as_euler('zxy', degrees=True), decimals=1)} (Other convention)")
print(f"Quaternions:      {np.around(rotation.as_quat(), decimals=3)}")
print(f"Rotation vectors: {np.around(rotation.as_rotvec(degrees=True), decimals=2)}")
print(f"Mod. Rod. Params: {np.around(rotation.as_mrp(), decimals=3)}")
print(f"Rotation matrix: \n {np.around(rotation.as_matrix(), decimals=3)}")

Euler angles:     [30. 45. 40.] (Bunge convention)
Euler angles:     [79.9 32.8 32.7] (Other convention)
Quaternions:      [0.381 0.033 0.53  0.757]
Rotation vectors: [47.61  4.17 66.18]
Mod. Rod. Params: [0.217 0.019 0.302]
Rotation matrix: 
 [[ 0.436 -0.777  0.455]
 [ 0.828  0.148 -0.542]
 [ 0.354  0.612  0.707]]


### A brief note on the representations we are going to use

TODO

In [5]:
import sys
import scipy as sp
import matplotlib as mpl
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)
print('Numpy', np.__version__)
print('Scipy', sp.__version__)
print('Matplolib', mpl.__version__)

Notebook tested in 2023-02-06 using:
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Numpy 1.23.5
Scipy 1.9.3
Matplolib 3.6.2
