# Basics of Scipy's rotation submodule

> **Goal**: Briefly explain all the common ways of representing a rotation in 3D Cartesian space and how it works using Scipy's Rotation submodule.. The purpose of using Scipy for rotations and not a specific library (e.g. https://dfki-ric.github.io/pytransform3d/) is to keep dependencies to a minimum (since Scipy will also be used for minimisation).

Scipy's rottaion module provides the following ways to represent rotations

- Rotation Matrices
- Euler Angles
- Quaternions
- Rotation Vectors (Euler axis and angle or simply axis-angle pair)
- Modified Rodrigues Parameters

as well as different operations on rotations and transformations between them. There is **no representation** that is non-redundant, continuous, and free of singularities. Below is a table summarising their properties:

|          **Representation**          |  **Inverse**  | **Rotation of vector** | **Concatenation** | **Interpolation** | **Scipy name** |
| :----------------------------------: | :-----------: | :--------------------: | :---------------: | :---------------: | :------------: |
|         Rotation matrix $R$          |   Transpose   |          Yes           |        Yes        |        No         |     matrix     |
| Euler angles ($\alpha,\beta,\gamma$) |      No       |           No           |        No         |        No         |     euler      |
|           Quaternion ($q$)           |   Conjugate   |          Yes           |        Yes        |        Yes        |      quat      |
|     Axis-angle ($\omega,\theta$)     | Negative axis |           No           |        No         |        Yes        |     rotvec     |
|         Rodrigues parameters         |               |                        |                   |                   |      mrp       |


For details more details see:  
https://dfki-ric.github.io/pytransform3d/rotations.html (most of the documentation here is based on this module)
https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as r

Rotations are defined by the following way:  

``r.from_<representation>(parameters)``  

where the representation of the rotation can be any of the types defined in the table (Scipy name) and the parameters to be entered depend on the type of representation: For example:

In [2]:
# define a rotation using Euler angles (Bunge convention)
rotation = r.from_euler('zxz', [30, 45, 40], degrees=True)

and transformed using:  

``r.as_<representation>(parameters)`` 

In [3]:
rotation.as_quat()

array([0.38122721, 0.03335306, 0.52991553, 0.75679781])

### A brief note on the representations we are going to use

TODO

In [4]:
print(f"Euler angles: {rotation.as_euler('zxz', degrees=True)} (Bunge convention)")
print(f"Euler angles: {rotation.as_euler('zxy', degrees=True)} (Other convention)")
print(f"Quaternions: {rotation.as_quat()}")
print(f"Rotation vectors: {rotation.as_rotvec(degrees=True)}")
print(f"Modified Rodrigues Parameters: {rotation.as_mrp()}")
print(f"Rotation matrix: \n {rotation.as_matrix()}")

Euler angles: [30. 45. 40.] (Bunge convention)
Euler angles: [79.87925979 32.79775133 32.73240721] (Other convention)
Quaternions: [0.38122721 0.03335306 0.52991553 0.75679781]
Rotation vectors: [47.61167346  4.16548168 66.18143918]
Modified Rodrigues Parameters: [0.21700119 0.01898514 0.30163718]
Rotation matrix: 
 [[ 0.43615421 -0.77664764  0.45451948]
 [ 0.82750801  0.1477107  -0.54167522]
 [ 0.35355339  0.61237244  0.70710678]]


In [5]:
np.around(rotation.as_quat(), decimals=4)

array([0.3812, 0.0334, 0.5299, 0.7568])

In [6]:
import sys
import scipy as sp
import matplotlib as mpl
from datetime import date    
today = date.today().isoformat()

print(f'Notebook tested in {today} using:')
print('Python', sys.version)
print('Numpy', np.__version__)
print('Scipy', sp.__version__)
print('Matplolib', mpl.__version__)

Notebook tested in 2023-02-03 using:
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Numpy 1.23.5
Scipy 1.9.3
Matplolib 3.6.2
